-- MySQL Script generated by MySQL Workbench
-- Mon Feb  6 20:11:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiktok
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiktok
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiktok` DEFAULT CHARACTER SET utf8 ;
USE `tiktok` ;

-- -----------------------------------------------------
-- Table `tiktok`.`UserInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiktok`.`UserInfo` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `follow_cnt` INT NULL,
  `follwer_cnt` INT NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiktok`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiktok`.`Video` (
  `id` INT NOT NULL,
  `author` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `play_url` VARCHAR(45) NULL,
  `cover_url` VARCHAR(45) NULL,
  `favorite_count` INT NULL,
  `comment_count` INT NULL,
  `create_time` DATETIME NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_Video_UserInfo1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Video_UserInfo1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tiktok`.`UserInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiktok`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiktok`.`Comment` (
  `id` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  `video_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `video_id`, `user_id`),
  INDEX `fk_Comment_Video1_idx` (`video_id` ASC),
  INDEX `fk_Comment_UserInfo1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Comment_Video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `tiktok`.`Video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_UserInfo1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tiktok`.`UserInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiktok`.`UserLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiktok`.`UserLogin` (
  `id` INT NOT NULL,
  `login_time` DATETIME NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_UserLogin_UserInfo1_idx` (`user_id` ASC),
  CONSTRAINT `fk_UserLogin_UserInfo1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tiktok`.`UserInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiktok`.`Follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiktok`.`Follow` (
  `follower_id` INT NOT NULL,
  `followed_id` INT NOT NULL,
  `followed_time` DATETIME NULL,
  PRIMARY KEY (`follower_id`, `followed_id`),
  INDEX `fk_UserInfo_has_UserInfo_UserInfo2_idx` (`followed_id` ASC),
  INDEX `fk_UserInfo_has_UserInfo_UserInfo1_idx` (`follower_id` ASC),
  CONSTRAINT `fk_UserInfo_has_UserInfo_UserInfo1`
    FOREIGN KEY (`follower_id`)
    REFERENCES `tiktok`.`UserInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserInfo_has_UserInfo_UserInfo2`
    FOREIGN KEY (`followed_id`)
    REFERENCES `tiktok`.`UserInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiktok`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiktok`.`Message` (
  `send_id` INT NOT NULL,
  `receive_id` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`send_id`, `receive_id`),
  INDEX `fk_UserInfo_has_UserInfo_UserInfo4_idx` (`receive_id` ASC),
  INDEX `fk_UserInfo_has_UserInfo_UserInfo3_idx` (`send_id` ASC),
  CONSTRAINT `fk_UserInfo_has_UserInfo_UserInfo3`
    FOREIGN KEY (`send_id`)
    REFERENCES `tiktok`.`UserInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserInfo_has_UserInfo_UserInfo4`
    FOREIGN KEY (`receive_id`)
    REFERENCES `tiktok`.`UserInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiktok`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiktok`.`Like` (
  `user_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  `like_time` DATETIME NULL,
  PRIMARY KEY (`user_id`, `video_id`),
  INDEX `fk_UserInfo_has_Video_Video1_idx` (`video_id` ASC),
  INDEX `fk_UserInfo_has_Video_UserInfo1_idx` (`user_id` ASC),
  CONSTRAINT `fk_UserInfo_has_Video_UserInfo1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tiktok`.`UserInfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserInfo_has_Video_Video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `tiktok`.`Video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
